rules:
  # job の name: は付けても付けなくてもよい
  anonymous-definition:
    disable: true

  # OP_SERVICE_ACCOUNT_TOKEN は 1Password 側で scope を絞っているので、GitHub Environment 無しで参照してよい
  secrets-outside-env:
    config:
      allow:
        - OP_SERVICE_ACCOUNT_TOKEN

  # caller repo は全て private なので、self-hosted runner を使ってよい
  self-hosted-runner:
    disable: true
