name: GitHub Actions

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  actions: read

jobs:
  github-actions:
    uses: ./.github/workflows/github-actions.yaml
