name: Pull Request title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions: {}

jobs:
  pull-request:
    permissions:
      pull-requests: write  # write: format revert PR titles, read: validate PR titles
    uses: ./.github/workflows/pull-request.yaml
