name: Pull Request title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  pr-title:
    uses: ./.github/workflows/pr-title.yaml
