name: secret-scan

on:
  workflow_call:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  secretlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Run secretlint
        # https://github.com/secretlint/secretlint
        #
        # To run locally, execute the following command:
        # docker run -v `pwd`:`pwd` -w `pwd` --rm -it secretlint/secretlint secretlint "**/*"
        uses: docker://secretlint/secretlint:v13.0.2@sha256:ce2d390b7961fb43d1d117a27ece88ac1fa5b1d866930ada484d67c108d159bd
        with:
          args: secretlint "**/*"
