name: secret-scan

on:
  workflow_call:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  secretlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run secretlint
        # https://github.com/secretlint/secretlint
        #
        # To run locally, execute the following command:
        # docker run -v `pwd`:`pwd` -w `pwd` --rm -it secretlint/secretlint secretlint "**/*"
        uses: docker://secretlint/secretlint:v12.3.1@sha256:47263811747c7e2bc0388549ba52aa4fd3e5f832a56e281f2d03212a9c859573
        with:
          args: secretlint "**/*"
