name: secretlint

on:
  workflow_call:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Secretlint
        # https://github.com/secretlint/secretlint
        #
        # To run locally, execute the following command:
        # docker run -v `pwd`:`pwd` -w `pwd` --rm -it secretlint/secretlint secretlint "**/*"
        uses: docker://secretlint/secretlint:v12.2.0@sha256:688b289e4c95c5f11a8883072edec9acd7e69b84e10730e4f98b7eb71b980007
        with:
          args: secretlint "**/*"
