name: secret-scan

on:
  workflow_call:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  secretlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run secretlint
        # https://github.com/secretlint/secretlint
        #
        # To run locally, execute the following command:
        # docker run -v `pwd`:`pwd` -w `pwd` --rm -it secretlint/secretlint secretlint "**/*"
        uses: docker://secretlint/secretlint:v13.0.2@sha256:ce2d390b7961fb43d1d117a27ece88ac1fa5b1d866930ada484d67c108d159bd
        with:
          args: secretlint "**/*"

  required:
    needs: [secretlint]
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Fail if any required job failed or was cancelled
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo "A required job failed or was cancelled"
          exit 1
